/** Declaration file generated by dts-gen */

export declare interface Contracts {
    WxRequestOptions: string;
    WxResponse: string;
    WxResponseData: string;
}

export as namespace MiniappMiddlewareContracts


